name: 'ci: Static Analysis'

on:
  push:
    - main
    - flat-file
    - eloquent
  pull_request:
    branches:
      - main

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install composer dependencies
        run: composer install -n --prefer-dist

      - name: Run Static Analysis
        run: ./vendor/bin/phpstan analyse app --error-format=github --memory-limit=512M
